<?php

/**
 * Implements hook_islandora_scholar_embargo_users_to_notify()
 */
function islandora_scholar_embargo_notification_manager_islandora_scholar_embargo_users_to_notify(AbstractObject $object) {

  // Hardcoded array for now, but later this should be an admin menu
  $parent_collection_array = array(
    "dev:repo" => array(
      2485,
      901,
    ),
  );

  // Get the parent collections from the embargoed object
  $xml_obj = simplexml_load_string($object['RELS-EXT']->content);
  $xml_obj->registerXPathNamespace('fedora', 'info:fedora/fedora-system:def/relations-external#');
  $xml_obj->registerXPathNamespace('rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#');
  $parents = $xml_obj->xpath('//fedora:isMemberOfCollection/@rdf:resource');
  $object_parents = array();
  foreach($parents as $parent) {
    $substr = str_replace(" rdf:resource=\"info:fedora/", "", $parent->asXML());
    $substr = rtrim($substr, '"');
    $object_parents[] = $substr;
  }
 
  // See if embargoed object's parents have extra users to be notified
  foreach($object_parents as $parent) {
    if(in_array($parent, array_keys($parent_collection_array))) {
      $users = user_load_multiple($parent_collection_array[$parent]);
    } else {
      $users = array();
    }
  }

  return $users;
}

