<?php

/**
 * Implements hook_islandora_scholar_embargo_users_to_notify()
 */
function islandora_scholar_embargo_notification_manager_islandora_scholar_embargo_users_to_notify(AbstractObject $object) {
}

/**
 * Implements hook_islandora_scholar_embargo_users_to_notify_alter()
 */
function islandora_scholar_embargo_notification_manager_islandora_scholar_embargo_users_to_notify_alter(array &$users, AbstractObject $object) {
}
